name: Deploy Next.js to Server

on:
  push:
    branches:
      - main  # จะ deploy เมื่อ push ไปที่ branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/iot_key
          chmod 600 ~/.ssh/iot_key
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='.github' \
            out/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/qoochubc/iot.qoochub.com/public_html/
