name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code and Build on Server
        run: |
          ssh -o StrictHostKeyChecking=no qoochubc@${{ secrets.STAGING_SERVER_IP }} << 'EOF_SERVER_OPS'
            cd /home/qoochubc/domains/iot.qoochub.com/public_html/

            git fetch origin main
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            echo 'Git pull completed on server.'

            source /home/qoochubc/domains/iot.qoochub.com/20/bin/activate
            echo 'Node.js virtual environment activated.'

            npm install --legacy-peer-deps || true
            echo 'Frontend dependencies installed on server.'

            npm run build
            echo 'Frontend assets built on server.'

            rsync -avz --delete \
                --exclude='.git' \
                --exclude='.github' \
              /home/qoochubc/domains/iot.qoochub.com/public_html/ \
              iot.qoochub.com/public_html/
            echo 'Public folder synced from SYSTEMSMSBKK to public_html.'
            
          EOF_SERVER_OPS

          echo 'Deploy completed.'
